In [3]:
# Function to perform basic mathematical operations
def calculate(expression):
    try:
        # Evaluate the mathematical expression
        result = eval(expression)
        return result
    except Exception as e:
        return f"Error: {str(e)}"

# Sample input
expression = "2.5+3.6"
# Get the result of the expression
result = calculate(expression)
# Print the result
print(f"The result of the expression {expression} is: {result}")


The result of the expression 2.5+3.6 is: 6.1


In [4]:
# Input dictionary
DIP = {'A': 1, 'B': 1, 'C': 2, 'D': 3, 'E': 2, 'F': 2, 'G': 3, 'H': 4, 'I': 3}

# Output dictionary
DOP = {}

# Iterate over the values in the input dictionary
for i in DIP.values():
    if i in DOP:
        DOP[i] += 1
    else:
        DOP[i] = 1

# Print the result
print(DOP)


{1: 2, 2: 3, 3: 3, 4: 1}


In [5]:
def count_values(input_dict):
    # Dictionary to store the frequency of each value
    value_count = {}

    # Populate the frequency dictionary
    for key, value in input_dict.items():
        if value in value_count:
            value_count[value] += 1
        else:
            value_count[value] = 1

    return value_count

# Sample input dictionary
input_dict = {
    's1': 'a',
    's2': 'b',
    's3': 'a',
    's4': 'b',
    's5': 'c',
    's6': 'b',
    's7': 'd'
}

# Count the values
result = count_values(input_dict)

# Print the result
for value, count in result.items():
    print(f"{value}={count}")


a=2
b=3
c=1
d=1


In [6]:
def addnum():
    a = int(input("Enter first number: "))
    b = int(input("Enter second number: "))
    c = a + b
    print("The sum is:", c)

if __name__ == "__main__":
    addnum()



Enter first number: 


ValueError: invalid literal for int() with base 10: ''

In [ ]:
def is_prime(n):
    """Check if a number is prime."""
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

if __name__ == "__main__":
    number = int(input("Enter a number to check if it is prime: "))
    if is_prime(number):
        print(f"{number} is a prime number.")
    else:
        print(f"{number} is not a prime number.")


In [ ]:
def is_palindrome(s):
    # Remove spaces and convert to lowercase for uniformity
    cleaned_string = ''.join(e for e in s if e.isalnum()).lower()

    # Check if the cleaned string is equal to its reverse
    return cleaned_string == cleaned_string[::-1]

# Example usage:
string = "A man, a plan, a canal, Panama"
if is_palindrome(string):
    print(f'"{string}" is a palindrome.')
else:
    print(f'"{string}" is not a palindrome.')


In [ ]:
list = ["o","p","p","o"]

copy_list = list.copy()
copy_list.reverse()

if(copy_list == list):
    print("Palindrome")

else:
    print("Not Palindrome")

In [7]:
l=list(map(str,input().split()))
print(l)


[]


In [8]:
l=tuple(map(str,input().split()))
print(l)


()


In [9]:
l=tuple(map(int,input().split()))
print(l)


()


In [10]:
class A:
    A = 1
    B = 2

    def __init__(self):
        self.a = 10
        self.b = 20

    def fun1(self):
        print("This is fun1 from class A")

    def printmember(self):
        # These lines will cause an error since x and y are not defined in class A
        # print(self.y)
        # print(self.x)
        pass

class B(A):
    def __init__(self):
        super().__init__()
        self.a = 11
        self.b = 22

    def fun1(self):
        super().fun1()
        print("This is fun1 from class B")

if __name__ == "__main__":
    obj = B()
    print(obj.a)
    print(obj.b)
    obj.fun1()
    print(obj.A)
    print(obj.B)


11
22
This is fun1 from class A
This is fun1 from class B
1
2


In [11]:
import numpy as np  # Import the NumPy library and give it the alias 'np'

Z = np.zeros(7)

Z

array([0., 0., 0., 0., 0., 0., 0.])

In [12]:
ar=np.array([1,2,3])
ar

array([1, 2, 3])

In [13]:
ran=np.random.rand(4)
ran

array([0.10683361, 0.25737583, 0.33471039, 0.47100639])

In [14]:
ln=np.linspace(0,100,10)
ln

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [15]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr2 = np.array([1,2,3,4,5], dtype=np.int16)

In [17]:
arr2

array([1, 2, 3, 4, 5], dtype=int16)

In [18]:
ar2=np.array([[1,2,3],[4,5,6]])
ar2

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
z1=np.zeros((5,5))
z1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
o1=np.ones((5,5))
z1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
I=np.eye(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
r1=np.random.rand(4,5)
r1

array([[0.43984522, 0.09195657, 0.05158619, 0.8576057 , 0.72624495],
       [0.90660152, 0.82244213, 0.71529934, 0.47172201, 0.97062079],
       [0.17290278, 0.24399706, 0.01734217, 0.33270907, 0.64224593],
       [0.19025841, 0.33819888, 0.47514663, 0.07216588, 0.2644157 ]])

In [23]:
import numpy as np # Import the NumPy library and give it the alias 'np'

ar = np.array([0,1,2,3,4,5,6,7,8,9]) # Use np.array to create NumPy arrays
ar2 = np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
print(ar2.size)

9


In [24]:
print(ar2.shape)

(3, 3)


In [25]:
ar3=np.copy(ar2)
ar3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
ar3[1,2]=12
ar3[0,1]=15
ar3

array([[ 1, 15,  3],
       [ 4,  5, 12],
       [ 7,  8,  9]])

In [27]:
ar3=np.sort(ar3)
ar3

array([[ 1,  3, 15],
       [ 4,  5, 12],
       [ 7,  8,  9]])

In [28]:
ar3=np.sort(ar3,axis=0)
ar3

array([[ 1,  3,  9],
       [ 4,  5, 12],
       [ 7,  8, 15]])

In [29]:
ar3.sum()

64

In [30]:
ar3.sum(axis=0)

array([12, 16, 36])

In [31]:
ar4=np.random.rand(99)

In [32]:
ar4.size

99

In [33]:
ar4=ar4.reshape(11,9)

In [34]:
ar4.size

99

In [35]:
ar4.shape

(11, 9)

In [36]:
ar3=ar3.T
ar3

array([[ 1,  4,  7],
       [ 3,  5,  8],
       [ 9, 12, 15]])

In [37]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.append(ar,10)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
ar=np.delete(ar,6,axis=0)

In [41]:
ar

array([0, 1, 2, 3, 4, 5, 7, 8, 9])

In [42]:
ar=np.insert(ar,6,6)

In [43]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
ar3

array([[ 1,  4,  7],
       [ 3,  5,  8],
       [ 9, 12, 15]])

In [46]:
ar4=np.concatenate((ar2,ar3),axis=0)
ar4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 1,  4,  7],
       [ 3,  5,  8],
       [ 9, 12, 15]])

In [47]:
ar5=np.concatenate((ar2,ar3),axis=1)
ar5

array([[ 1,  2,  3,  1,  4,  7],
       [ 4,  5,  6,  3,  5,  8],
       [ 7,  8,  9,  9, 12, 15]])

In [48]:
ar6=np.split(ar4,3)
ar6

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9],
        [1, 4, 7]]),
 array([[ 3,  5,  8],
        [ 9, 12, 15]])]

In [49]:
ar6[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
ar6[1]

array([[7, 8, 9],
       [1, 4, 7]])

In [51]:
ar6[2]

array([[ 3,  5,  8],
       [ 9, 12, 15]])

In [52]:
ar6[0][0][0]

1

In [53]:
np.add(ar5,1)

array([[ 2,  3,  4,  2,  5,  8],
       [ 5,  6,  7,  4,  6,  9],
       [ 8,  9, 10, 10, 13, 16]])

In [54]:
np.subtract(ar5,1)

array([[ 0,  1,  2,  0,  3,  6],
       [ 3,  4,  5,  2,  4,  7],
       [ 6,  7,  8,  8, 11, 14]])

In [55]:
np.multiply(ar5,1)

array([[ 1,  2,  3,  1,  4,  7],
       [ 4,  5,  6,  3,  5,  8],
       [ 7,  8,  9,  9, 12, 15]])

In [56]:
np.divide(ar5,1)

array([[ 1.,  2.,  3.,  1.,  4.,  7.],
       [ 4.,  5.,  6.,  3.,  5.,  8.],
       [ 7.,  8.,  9.,  9., 12., 15.]])

In [57]:
np.power(ar5,1)

array([[ 1,  2,  3,  1,  4,  7],
       [ 4,  5,  6,  3,  5,  8],
       [ 7,  8,  9,  9, 12, 15]])

In [58]:
np.power(ar5,2)

array([[  1,   4,   9,   1,  16,  49],
       [ 16,  25,  36,   9,  25,  64],
       [ 49,  64,  81,  81, 144, 225]])

In [59]:
ar7=np.add(ar6[0],ar6[1])
print(ar7) # Print the result of the addition instead of trying to access an undefined variable

[[ 8 10 12]
 [ 5  9 13]]


In [60]:
ar8=np.multiply(ar6[0],ar6[1])
print(ar8)

[[ 7 16 27]
 [ 4 20 42]]


In [61]:
ar9=np.divide(ar6[0],ar6[1])
print(ar9)

[[0.14285714 0.25       0.33333333]
 [4.         1.25       0.85714286]]


In [62]:
np.ceil(ar9)

array([[1., 1., 1.],
       [4., 2., 1.]])

In [63]:
np.floor(ar9)

array([[0., 0., 0.],
       [4., 1., 0.]])

In [64]:
np.round(ar9)

array([[0., 0., 0.],
       [4., 1., 1.]])

In [65]:
np.mean(ar5)

6.055555555555555

In [66]:
np.mean(ar5,axis=1)

array([ 3.        ,  5.16666667, 10.        ])

In [67]:
np.median(ar5,axis=1)

array([2.5, 5. , 9. ])

In [68]:
np.min(ar5)

1

In [69]:
np.min(ar5,axis=0)

array([1, 2, 3, 1, 4, 7])

In [70]:
np.max(ar5,axis=0)

array([ 7,  8,  9,  9, 12, 15])

In [71]:
ar10=np.array([1,2,3,4,5,6,7,8,9])
ar10

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
np.argmax(ar10)

8

In [73]:
np.argmin(ar10)

0

In [74]:
np.argsort(ar10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [75]:
np.sin(ar10)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [76]:
np.log(ar10)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [77]:
import numpy as np  # Import the NumPy library and give it the alias 'np'
ar11 = np.array([[85, 90, 78],
       [92, 88, 95],
       [76, 95, 85],
       [76, 95, 85],
       [90, 85, 92],
       [88, 76, 89]])

In [78]:
np.mean(ar11)

86.66666666666667

In [79]:
np.median(ar11)

88.0

In [80]:
np.min(ar11)

76

In [81]:
np.max(ar11)

95

In [82]:
ar11=ar11.reshape(2,9)
ar11

array([[85, 90, 78, 92, 88, 95, 76, 95, 85],
       [76, 95, 85, 90, 85, 92, 88, 76, 89]])

In [83]:
ar11 = np.array([[85, 90, 78],
       [92, 88, 95],
       [76, 95, 85],
       [76, 95, 85],
       [90, 85, 92],
       [88, 76, 89]])

In [86]:
ar11.sort()
ar11

array([[78, 85, 90],
       [88, 92, 95],
       [76, 85, 95],
       [76, 85, 95],
       [85, 90, 92],
       [76, 88, 89]])

In [87]:
def divide_numbers(a, b):
    try:
        result = a / b
    except ZeroDivisionError as e:
        print("Error: Cannot divide by zero.")
        result = None
    except TypeError as e:
        print("Error: Invalid input type.")
        result = None
    else:
        print(f"Result: {result}")
    finally:
        print("Execution completed.")
    return result

# Test the function
print(divide_numbers(10, 2))
print(divide_numbers(10, 0))
print(divide_numbers(10, 'a'))

Result: 5.0
Execution completed.
5.0
Error: Cannot divide by zero.
Execution completed.
None
Error: Invalid input type.
Execution completed.
None


In [88]:
a = 10
b = 5

try:
    print(a / b)
except ZeroDivisionError:
    print("Error: Division by zero is not allowed.")
except NameError:
    print("Error: A variable is not defined.")
except IndexError:
    print("Error: Index out of range.")


2.0


In [89]:
a = 10
b = 10
try:
    print(a / b)  # This will raise ZeroDivisionError
    print(c)  # This will raise NameError
    lst = [1, 2, 3]
    print(lst[5])  # This will raise IndexError
except ZeroDivisionError:
    print("Error: Division by zero is not allowed.")
except NameError:
    print("Error: A variable is not defined.")
except IndexError:
    print("Error: Index out of range.")


1.0
Error: A variable is not defined.


In [90]:
a = 10
b = 2

try:
    # print(a / b)  # This will raise ZeroDivisionError
    print(c)  # This will raise NameError
    lst = [1, 2, 3]
    print(lst[5])  # This will raise IndexError
except ZeroDivisionError:
    print("Error: Division by zero is not allowed.")
except NameError:
    print("Error: A variable is not defined.")
except IndexError:
    print("Error: Index out of range.")


Error: A variable is not defined.


In [91]:
# ZeroDivisionError
try:
    result = 10 / 0
except ZeroDivisionError as e:
    print(f"Caught an error: {e}")

# NameError
try:
    print(unknown_variable)
except NameError as e:
    print(f"Caught an error: {e}")

# IndexError
my_list = [1, 2, 3]
try:
    print(my_list[3])
except IndexError as e:
    print(f"Caught an error: {e}")


Caught an error: division by zero
Caught an error: name 'unknown_variable' is not defined
Caught an error: list index out of range


In [92]:
disc={
    "Name":["RAM","SHAM","CARRY","VANSHIKA","ADII"],
    "Roll no":[1,2,3,4,5],
    "Grades":["A","B","C","D","A"],
    "Emails":["ram@gmai;.com","sham@gmail.com","carr@gmail.com","van@gmail.com","adii@gmail.com"]
}

In [93]:
!pip install pandas
import pandas as pd

df = pd.DataFrame(disc)
df

Name  Roll no Grades          Emails
0       RAM        1      A   ram@gmai;.com
1      SHAM        2      B  sham@gmail.com
2     CARRY        3      C  carr@gmail.com
3  VANSHIKA        4      D   van@gmail.com
4      ADII        5      A  adii@gmail.com

In [94]:
df.head(2)

Name  Roll no Grades          Emails
0   RAM        1      A   ram@gmai;.com
1  SHAM        2      B  sham@gmail.com

In [95]:
df.tail(2)

Name  Roll no Grades          Emails
3  VANSHIKA        4      D   van@gmail.com
4      ADII        5      A  adii@gmail.com

In [96]:
import random

# Sample data
company_names = ["Company A", "Company B", "Company C", "Company D", "Company E"]
employee_names = [
    "John Smith", "Jane Doe", "Alice Johnson", "Chris Evans", "Jessica Brown",
    "Michael Scott", "Pam Beesly", "Jim Halpert", "Dwight Schrute", "Angela Martin",
    "Oscar Martinez", "Stanley Hudson", "Phyllis Vance", "Meredith Palmer", "Ryan Howard",
    "Kelly Kapoor", "Toby Flenderson", "Creed Bratton", "Holly Flax", "Jan Levinson",
    "David Wallace", "Darryl Philbin", "Andy Bernard", "Gabe Lewis", "Erin Hannon",
    "Clark Green", "Pete Miller", "Nellie Bertram", "Robert California", "Jo Bennett",
    "Charles Miner", "Roy Anderson", "Carol Stills", "Hannah Smoterich", "Karen Filippelli",
    "Karen S", "Leo L", "Gino K", "Sam K", "John D", "Alex F", "Lisa M", "Tom N",
    "Gary T", "Lisa B", "Ben K", "Emily S", "Phil L", "Sandra D"
]
positions = [
    "Manager", "Assistant Manager", "Salesperson", "Accountant", "HR",
    "Receptionist", "Engineer", "Developer", "Designer", "Analyst"
]

# Generate 50 entries
data = {
    f"entry_{i+1}": {
        "Company Name": random.choice(company_names),
        "Employee Name": random.choice(employee_names),
        "Position": random.choice(positions)
    }
    for i in range(50)
}

# Print the generated dictionary
for key, value in data.items():
    print(f"{key}: {value}")


entry_1: {'Company Name': 'Company C', 'Employee Name': 'John Smith', 'Position': 'Developer'}
entry_2: {'Company Name': 'Company C', 'Employee Name': 'Pam Beesly', 'Position': 'Salesperson'}
entry_3: {'Company Name': 'Company D', 'Employee Name': 'Creed Bratton', 'Position': 'Receptionist'}
entry_4: {'Company Name': 'Company A', 'Employee Name': 'Sam K', 'Position': 'Manager'}
entry_5: {'Company Name': 'Company C', 'Employee Name': 'Creed Bratton', 'Position': 'Developer'}
entry_6: {'Company Name': 'Company A', 'Employee Name': 'Creed Bratton', 'Position': 'Assistant Manager'}
entry_7: {'Company Name': 'Company A', 'Employee Name': 'Sandra D', 'Position': 'Developer'}
entry_8: {'Company Name': 'Company E', 'Employee Name': 'Lisa M', 'Position': 'Receptionist'}
entry_9: {'Company Name': 'Company D', 'Employee Name': 'John Smith', 'Position': 'Receptionist'}
entry_10: {'Company Name': 'Company A', 'Employee Name': 'Gino K', 'Position': 'HR'}
entry_11: {'Company Name': 'Company B', 'Empl

In [ ]:
df=pd.DataFrame(data)
df

entry_1         entry_2     entry_3       entry_4  \
Company Name     Company C       Company A   Company C     Company D   
Employee Name      Emily S  Nellie Bertram       Ben K       Emily S   
Position       Salesperson        Engineer  Accountant  Receptionist   

                         entry_5     entry_6        entry_7       entry_8  \
Company Name           Company D   Company D      Company A     Company A   
Employee Name   Karen Filippelli  Pam Beesly  Michael Scott       Karen S   
Position       Assistant Manager     Analyst        Manager  Receptionist   

                 entry_9    entry_10  ...    entry_41   entry_42  \
Company Name   Company B   Company D  ...   Company C  Company B   
Employee Name      Tom N  Pam Beesly  ...  Pam Beesly     John D   
Position         Manager          HR  ...     Manager   Designer   

                    entry_43     entry_44           entry_45      entry_46  \
Company Name       Company B    Company B          Company E     Company C   
Employee Name  Michael Scott  Clark Green              Ben K  Jan Levinson   
Position             Manager    Developer  Assistant Manager      Engineer   

                   entry_47   entry_48        entry_49          entry_50  
Company Name      Company A  Company D       Company C         Company D  
Employee Name  Roy Anderson      Ben K  Oscar Martinez  Hannah Smoterich  
Position        Salesperson   Designer        Engineer                HR  

[3 rows x 50 columns]

In [ ]:
cd=pd.DataFrame(data)
cd

entry_1         entry_2     entry_3       entry_4  \
Company Name     Company C       Company A   Company C     Company D   
Employee Name      Emily S  Nellie Bertram       Ben K       Emily S   
Position       Salesperson        Engineer  Accountant  Receptionist   

                         entry_5     entry_6        entry_7       entry_8  \
Company Name           Company D   Company D      Company A     Company A   
Employee Name   Karen Filippelli  Pam Beesly  Michael Scott       Karen S   
Position       Assistant Manager     Analyst        Manager  Receptionist   

                 entry_9    entry_10  ...    entry_41   entry_42  \
Company Name   Company B   Company D  ...   Company C  Company B   
Employee Name      Tom N  Pam Beesly  ...  Pam Beesly     John D   
Position         Manager          HR  ...     Manager   Designer   

                    entry_43     entry_44           entry_45      entry_46  \
Company Name       Company B    Company B          Company E     Company C   
Employee Name  Michael Scott  Clark Green              Ben K  Jan Levinson   
Position             Manager    Developer  Assistant Manager      Engineer   

                   entry_47   entry_48        entry_49          entry_50  
Company Name      Company A  Company D       Company C         Company D  
Employee Name  Roy Anderson      Ben K  Oscar Martinez  Hannah Smoterich  
Position        Salesperson   Designer        Engineer                HR  

[3 rows x 50 columns]

In [ ]:
cd.drop_duplicates(subset=list(cd.columns), keep=False)

entry_1         entry_2     entry_3       entry_4  \
Company Name     Company C       Company A   Company C     Company D   
Employee Name      Emily S  Nellie Bertram       Ben K       Emily S   
Position       Salesperson        Engineer  Accountant  Receptionist   

                         entry_5     entry_6        entry_7       entry_8  \
Company Name           Company D   Company D      Company A     Company A   
Employee Name   Karen Filippelli  Pam Beesly  Michael Scott       Karen S   
Position       Assistant Manager     Analyst        Manager  Receptionist   

                 entry_9    entry_10  ...    entry_41   entry_42  \
Company Name   Company B   Company D  ...   Company C  Company B   
Employee Name      Tom N  Pam Beesly  ...  Pam Beesly     John D   
Position         Manager          HR  ...     Manager   Designer   

                    entry_43     entry_44           entry_45      entry_46  \
Company Name       Company B    Company B          Company E     Company C   
Employee Name  Michael Scott  Clark Green              Ben K  Jan Levinson   
Position             Manager    Developer  Assistant Manager      Engineer   

                   entry_47   entry_48        entry_49          entry_50  
Company Name      Company A  Company D       Company C         Company D  
Employee Name  Roy Anderson      Ben K  Oscar Martinez  Hannah Smoterich  
Position        Salesperson   Designer        Engineer                HR  

[3 rows x 50 columns]

In [ ]:
class Record:
    def __init__(self):
        self.name = ""
        self.id = 0
        self.eid = 0
        self.ename = ""
        self.status = ""
        self.condition = ""

    def rented(self):
        self.name = input("Enter your Name: ")
        self.id = int(input("Enter id: "))
        self.eid = int(input("Enter eid: "))
        self.ename = stock[self.eid][0]
        self.status = "Rented"
        self.condition = "Good"
        Records[self.id] = [self.name, self.ename, self.status, self.condition]

    def return_equip(self):
        self.id = int(input("Enter id: "))
        print("Member id =", self.id)
        if self.id in Records:
            self.status = "Returned"
            self.condition = input("Enter condition of the equipment: ")
            Records[self.id][2] = self.status
            Records[self.id][3] = self.condition
        else:
            print("No record found for this id.")

# Sample dictionary to simulate the stock
stock = {
    1: ["Drill"],
    2: ["Hammer"],
    3: ["Saw"]
}

# Sample dictionary to simulate the records
Records = {}

# Example usage
record = Record()
record.rented()
record.return_equip()

# Display Records
print(Records)
