In [1]:
import numpy as np

In [2]:
scores = np.array([[85, 90, 78],
                   [92, 88, 95],
                   [76, 95, 85],
                   [90, 85, 92],
                   [88, 76, 89]])

In [3]:
scores

array([[85, 90, 78],
       [92, 88, 95],
       [76, 95, 85],
       [90, 85, 92],
       [88, 76, 89]])

In [4]:
mean_scores = np.mean(scores, axis=0)
print("Mean scores for each subject:", mean_scores)

Mean scores for each subject: [86.2 86.8 87.8]


In [5]:
mean_scores = np.median(scores, axis=0)
print("Mean scores for each subject:", mean_scores)

Mean scores for each subject: [88. 88. 89.]


In [9]:
total_scores = np.sum(scores, axis=1)
index_of_highest_total = np.argmax(total_scores)
highest_total_scores = scores[index_of_highest_total]
print("Total scores of each student:", total_scores)
print("Scores of the student with the highest total score:", highest_total_scores)

Total scores of each student: [253 275 256 267 253]
Scores of the student with the highest total score: [92 88 95]


In [10]:
max_scores = np.max(scores, axis=0)
min_scores = np.min(scores, axis=0)
print("Maximum scores for each subject:", max_scores)
print("Minimum scores for each subject:", min_scores)

Maximum scores for each subject: [92 95 95]
Minimum scores for each subject: [76 76 78]


In [11]:
transposed_scores = scores.T
reshaped_scores = transposed_scores.reshape(3, 5)
print("Reshaped array:")
print(reshaped_scores)

Reshaped array:
[[85 92 76 90 88]
 [90 88 95 85 76]
 [78 95 85 92 89]]
